mutation  {{
  destroyItem(input: {{itemId:"{0}"}})

{{
  destroyed
  ...MutationForm_mutationErrors
}}
}}

fragment MutationForm_mutationErrors on StandardMutationPayload {{
  attributeErrors {{
    path
    type
    messages
  }}
  globalErrors {{
    message
  }}
  errors {{
    message
  }}
}}