mutation {{
  applySchemaProperties(input: {{
      entityId: "{0}",
      propertyValues: {{
        pdf_version: "{1}",
        }}
      }}
  )

    {{
        item {{
            id
      }}
        schemaErrors {{
          path
          message
        }}
    }}
}}