mutation {{
  updatePersonContributor(input: {{
	  givenName: "{0}",
	  familyName: "{1}",
	  affiliation: "{2}"
	  email: "{3}"
	  contributorId: "{4}"
	}}) {{
	  contributor {{
	    id
	    givenName
	    slug
	  }}
	}}
}}