mutation {{
  applySchemaProperties(input: {{
      entityId: "{0}",
      propertyValues: {{
        abstract: "{1}",
        publisher: "{5}",
        advisor: "{4}",
        graduation_date: "{3}",
        language: "English",
        access: "{6}",
        pdf_version: "{7}",
        degree : {{
          level: "{2}",
            grantor: "{5}"
        }}
      }}
  }})

    {{
        item {{
            id
      }}
        schemaErrors {{
          path
          message
        }}
    }}
}}